### ISSUE TITLE
[Bug] Moderate and critical vulnerabilities in dependent packages

### ISSUE THREAD

**Issue by dmvt** [ArkEcosystem/core-plugin-skeleton#7]
**Describe the bug**

There a moderate and high security vulnerabilities in the dependency packages.
```
found 147 vulnerabilities (65 low, 70 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**To Reproduce**
1. Go to terminal
2. run `npm install`
3. See error

**Expected behavior**

There should not be any moderate or high vulnerabilities if it can be avoided.

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
